const TRAD_EN = {
  title: '13 STEPS TO ESCAPE',
  continue: 'CONTINUE',
  newGame: 'NEW GAME',
  levelSelection: 'LEVEL SELECTION',
  options: 'OPTIONS',
  characterCustomization: 'CHARACTER CUSTOMIZATION',
  steps: 'STEPS',
  level: 'LEVEL',
  undo: 'E: UNDO',
  reset: 'R: RESET',
  congratulations: 'CONGRATULATIONS!',
  allLevelsCompleted: 'YOU ESCAPED ALL LEVELS WITHIN 13 STEPS!',
  selectGender: 'SELECT GENDER',
  selectSkin: 'SELECT SKIN COLOR',
  selectHair: 'SELECT HAIR COLOR',
  selectOutfit: 'SELECT OUTFIT COLOR',
  boy: 'BOY',
  girl: 'GIRL',
  language: 'LANGUAGE',
  volume: 'VOLUME',
  sound: 'SOUND',
  back: 'BACK',
};
