const TRAD_FR = {
  title: '13 PAS POUR S ECHAPPER',
  continue: 'CONTINUER',
  newGame: 'NOUVELLE PARTIE',
  levelSelection: 'SELECTION DU NIVEAU',
  options: 'OPTIONS',
  characterCustomization: 'PERSONNALISATION',
  steps: 'PAS',
  level: 'NIVEAU',
  undo: 'E: ANNULER',
  reset: 'R: RECOMMENCER',
  congratulations: 'FELICITATIONS!',
  allLevelsCompleted: 'VOUS AVEZ ECHAPPE A TOUS LES NIVEAUX EN 13 PAS!',
  selectGender: 'CHOISIS TON PERSONNAGE',
  selectSkin: 'COULEUR DE PEAU',
  selectHair: 'COULEUR DE CHEVEUX',
  selectOutfit: 'COULEUR DE TENUE',
  boy: 'GARCON',
  girl: 'FILLE',
  language: 'LANGUE',
  volume: 'VOLUME',
  sound: 'SON',
  back: 'RETOUR',
};
